version: '3.8'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    restart: always
    tty: true
    networks:
      - fullcycle
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db    

  db:
    image: mysql:5.7   
    command: --innodb-use-native-aio=0 
    restart: always
    tty: true
    networks:
      - fullcycle
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      - app

networks:
  fullcycle:
    driver: bridge